name = "stage-auth"
type = "javascript"

zone_id = "0f02aded663a88d4e31276b250ecc1e1"
account_id = "44cb8adab02ef7b388b48091a6be4673"
route = "stage.saladsimulator.com/*"
workers_dev = true

[vars]
AUTH0_CLIENT_ID = "bwTWTXSpIJ5jIblPWxN278bU06J25ine"
BASE_URL = 'https://stage.saladsimulator.com'
AUTH0_BASE_URL = 'https://staging-saladsimulator.au.auth0.com'
AUTH0_API_AUDIENCE = 'saladsimulator-staging'

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "AUTH_STORE"
preview_id = "83975a1ccf2940708cc74ee562486905"
id = "34b4a37c73dc489b8f5ac88daec94fc8"